services:
  - type: web
    name: flask-daily-checkin
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
