"""Add ChartEntry model

Revision ID: d36895c9b025
Revises: 288dd5097e6b
Create Date: 2025-08-07 09:23:16.823035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36895c9b025'
down_revision = '288dd5097e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('sheet', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_entries_client_name'), ['client_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_entries_client_name'))

    op.drop_table('chart_entries')
    # ### end Alembic commands ###
