"""Add updated_at to chart_entries

Revision ID: f99fcc5002c4
Revises: d36895c9b025
Create Date: 2025-08-07 22:59:57.918356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99fcc5002c4'
down_revision = 'd36895c9b025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('client_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_chart_entries_sheet'), ['sheet'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_entries_sheet'))
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
